modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "improvedmapcolors"
version = "${version}"
displayName = "ImprovedMapColors"
authors = "gamma_02, Gneiss Name, Grassy"
description = '''

'''
logoFile = "icon.png"

[[dependencies.improvedmapcolors]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.improvedmapcolors]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.improvedmapcolors]]
modId = "architectury"
type = "required"
versionRange = "[17.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "improvedmapcolors.mixins.json"
